### ISSUE TITLE
1: ExtendedAttributeNoArgs not supported: "Wrapped"', bindgen\src/lib.rs:79:6

### ISSUE THREAD

**Issue by ruskpr** [NordSecurity/uniffi-bindgen-cs#16]
I'm getting the following error message when I try to run uniffi-bindgen-cs against 
```
https://github.com/sicpa-dlab/didcomm-rust/blob/main/uniffi/src/didcomm.udl#L1
```
1: ExtendedAttributeNoArgs not supported: "Wrapped"', bindgen\src/lib.rs:79:6

Does anybody know how we can work around this?

**Comment by arg0d** [comment]
Hey, it looks like your .udl files contains an extended attribute "Wrappped", which is not supported in uniffi-rs version 0.23.0 (the version I checked with). How are you getting this to work when generating Rust scaffolding? Which uniffi-rs verison are you using? Is this an issue only with `uniffi-bindgen-cs`?

**Comment by ruskpr** [comment]
Found the solution in https://mozilla.github.io/uniffi-rs/udl/custom_types.html it had everything I needed to resolve the issue.

 I changed ```[Wrapped]``` with ```[Custom]```, as it provides the similar functionality, just in a different name in the newer versions of ```uniffi-rs```.
