### ISSUE TITLE
uniffi-bindgen-cs sample or tutorial?

### ISSUE THREAD

**Issue by mwherman2000** [NordSecurity/uniffi-bindgen-cs#18]
Where can I find a worked uniffi-bindgen-cs sample or tutorial? Thank you

**Comment by arg0d** [comment]
Do you have a specific question in mind? The usage is the same as with `mozilla/uniffi-rs`. Basic instructions are available in the main [REAMDE.md](https://github.com/NordSecurity/uniffi-bindgen-cs). There is also [C# automated test project](https://github.com/NordSecurity/uniffi-bindgen-cs/tree/main/dotnet-tests) and [tests](https://github.com/NordSecurity/uniffi-bindgen-cs/tree/main/dotnet-tests/UniffiCS.binding_tests).

**Comment by mwherman2000** [comment]
Our scenario is that we're mostly/only C#/.NET developers and we need to be able to call into a Rust module/project: https://github.com/sicpa-dlab/didcomm-rust

This project supports a few different calling environments but not C#.  We're looking for some direction into how to process this library with uniffi-bindgen-cs.  My guess is that we need to know how to construct a .UDL file for this library that is C# compatible?

**Comment by filipw** [comment]
I wrote a simple tutorial if someone is interested https://www.strathweb.com/2023/06/calling-rust-code-from-csharp/

**Comment by mwherman2000** [comment]
Closed with @filipw 's tutorial.  Thank you.
