### ISSUE TITLE
Does this tool have an equivalent flag to `--lib-file` from the UniFFI Bindgen CLI?

### ISSUE THREAD

**Issue by 0xOmarA** [NordSecurity/uniffi-bindgen-cs#20]
Hi, I'm currently using the new [experimental macro features](https://mozilla.github.io/uniffi-rs/proc_macro/index.html) from the UniFFI toolkit instead of writing out a .udl file by hand. In this approach the information needed to generate the bindings is all stored in the static or dynamic library and we need to specify a static or dynamic library through the `--lib-file` flag on the UniFFI bindgen tool during generation time.

Looking at this tool, I do not see support for a `--lib-file` flag or an equivalent. Does the CSharp generator currently support this? If not, does the team plan on adding support for this in the future?

**Comment by arg0d** [comment]
Hey, `--lib-file` will be added eventually once procedural macros become more finished, though I'm not sure when exactly. I will try to update `uniffi-bindgen-cs` to 0.24.0 upstream in the next month or so, and try to catch up with command line options, including `--lib-file`.

**Comment by 0xOmarA** [comment]
@arg0d Fantastic, thank you!

**Comment by meenzen** [comment]
I think I've run into this exact issue when trying to generate bindings for the [matrix-rust-sdk](https://github.com/matrix-org/matrix-rust-sdk/tree/main/bindings%2Fmatrix-sdk-ffi). I'm looking forward to the `--lib-file` support, it'll be a good test of the capabilities this tool offers.

Thanks for the hard work.

**Comment by 0xOmarA** [comment]
@meenzen Are you on 0.24.0 or 0.24.1 of Uniffi-rs as well? I was thinking of writing a tool to extract the UniFFI interface definition from the dynamic library and into a .udl file, but it seems like this would not be of much use because of the [version in-compatibility](https://github.com/NordSecurity/uniffi-bindgen-cs#versioning) between this generator and the uniffi-rs version.

**Comment by 0xOmarA** [comment]
Closing this issue as I see that the recent v0.6.0 has support for extracting the interface definition from the library files: https://github.com/NordSecurity/uniffi-bindgen-cs/blob/main/bindgen/src/lib.rs#L29-L35. Thank you for adding this!
