### ISSUE TITLE
Option to generate internal APIs

### ISSUE THREAD

**Issue by AArnott** [NordSecurity/uniffi-bindgen-cs#23]
The generated .cs file seems to include mostly `internal` types. But the class that contains the exported functions themselves is public. I don't want to expose these bare metal functions to folks who reference my assembly.
Can you add an option to emit all `internal` types?

**Comment by AArnott** [comment]
`_UniFFILib` is already internal. But the `*Methods` class is public, which is a problem.

**Comment by AArnott** [comment]
I see exception types are generated as public as well, which I need to be internal. Essentially the option I'm asking for should suppress _all_ use of `public` for generated types.

**Comment by arg0d** [comment]
I see, I understand now. There should be an option to change the modifier for "public" bindings fields. I guess this includes objects and callbacks as well? As I understand the use case is the following: add generated Uniffi C# bindings file to an existing C# project, but don't expose Uniffi bindings to C# project consumers.

**Comment by AArnott** [comment]
Yes, exactly. My C# project provides high level APIs that depend on bindings to rust. I don't want to expose _any_ of those low-level bindings to my own users.
