### ISSUE TITLE
How to generate DllImport attributes with the right library name?

### ISSUE THREAD

**Issue by AArnott** [NordSecurity/uniffi-bindgen-cs#24]
Following the instructions in the README, I get code like this:

```cs
    [DllImport("uniffi")]
    public static extern uint sapling_c3fe_add(uint @a,uint @b,
    ref RustCallStatus _uniffi_out_err
    );
```

But my library isn't called `uniffi`. How do I change this?

**Comment by AArnott** [comment]
Although it isn't documented here, I found [an example config toml file](https://github.com/NordSecurity/uniffi-bindgen-cs/blob/4bc2bf6c9d243bc34529cba16b6f5bd47cdf6b2a/uniffi-test-fixtures.toml#L2) in this repo. But creating that file and adding `-c uniffi.toml` to my generation script doesn't appear to change the name of the library in the DllImport attribute.

**Comment by AArnott** [comment]
I guess that's just the beginning of the mismatches, because after I manually fix this up, it fails because `sapling_c3fe_add` isn't exported from rust. The closest match seems to be `uniffi_sapling_fn_func_add`.

**Comment by arg0d** [comment]
> Although it isn't documented here, I found [an example config toml file](https://github.com/NordSecurity/uniffi-bindgen-cs/blob/4bc2bf6c9d243bc34529cba16b6f5bd47cdf6b2a/uniffi-test-fixtures.toml#L2) in this repo. But creating that file and adding `-c uniffi.toml` to my generation script doesn't appear to change the name of the library in the DllImport attribute.

Yes, you can use `cdylib_name` to customize bindings to use desired library name. This should added to README.md.

**Comment by arg0d** [comment]
> I guess that's just the beginning of the mismatches, because after I manually fix this up, it fails because `sapling_c3fe_add` isn't exported from rust. The closest match seems to be `uniffi_sapling_fn_func_add`.

Which version of uniffi-bindgen-cs are you using? 0.2.2 had incompatibility issue with upstream. Should be fixed in 0.2.3.

**Comment by arg0d** [comment]
Also make sure that you are using correct versions, the latest compatible versions are 0.2.3 uniffi-bindgen-cs for generating C# bindings, and 0.23.0 uniffi-rs for building the Rust code.

**Comment by AArnott** [comment]
> Which version of uniffi-bindgen-cs are you using? 

I don't know. I used the `cargo install uniffi-bindgen-cs --git https://github.com/NordSecurity/uniffi-bindgen-cs` command as prescribed in the readme. As I imagine that varies over time, I'll add that I ran this command in the last two days.

>  and 0.23.0 uniffi-rs for building the Rust code.

I had been using uniffi 0.24.3. But I downgraded to 0.23.0 just now based on your recommendation. But I doubt that was causing my problem because the uniffi crate that I select isn't used when generating C# code, right?

> the latest compatible versions are 0.2.3 uniffi-bindgen-cs for generating C# bindings

As I said, I was just following the README of this repo to install the latest from your git repo. But when I try to install the specific version you recommend here, I get an error:

```
 cargo install uniffi-bindgen-cs --version 0.2.3
    Updating crates.io index
error: could not find `uniffi-bindgen-cs` in registry `crates-io` with version `=0.2.3`
```

So then I got creating and tried this (I'm quite new at all this):

```
cargo install uniffi-bindgen-cs --git https://github.com/NordSecurity/uniffi-bindgen-cs --tag v0.2.3+v0.23.0
```

That seemed to complete alright.
I like your recent tag naming scheme as that seems to make it clear what the `uniffi` version should be as well.

And in fact now the generated code has the right `DllImport` attribute and exported function name, so all is well. 

Thank you for your help. Updating the readme to indicate that we should install a specific tag from your repo, and match it with a particular version from `uniffi` may save the future soul some trouble. 

And thanks so much for the C# bindings generator. I expect this will save me lots of time.

**Comment by arg0d** [comment]
Thanks for you input, I will keep this issue open until we update README.md to include:
```
cargo install uniffi-bindgen-cs --git https://github.com/NordSecurity/uniffi-bindgen-cs --tag v0.2.3+v0.23.0
```

We should also probably publish this package to crates.io, but we haven't had the time to do that yet :sweat_smile:

**Comment by arg0d** [comment]
Things to do:
- [ ] Update README.md with `cargo install uniffi-bindgen-cs --git https://github.com/NordSecurity/uniffi-bindgen-cs --tag v0.2.3+v0.23.0`
- [ ] Update README.md to document available settings, e.g. `cdylib_name`
