### ISSUE TITLE
junk remaining in buffer after lifting, something is very wrong!!

### ISSUE THREAD

**Issue by AArnott** [NordSecurity/uniffi-bindgen-cs#72]
Oh dear. I saw this today:

```
uniffi.LightWallet.InternalException
  HResult=0x80131500
  Message=junk remaining in buffer after lifting, something is very wrong!!
  Source=Nerdbank.Zcash
  StackTrace:
   at uniffi.LightWallet.FfiConverter`2.LiftFromRustBuffer(RustBuffer rbuf) in C:\git\Nerdbank.Cryptocurrencies\src\Nerdbank.Zcash\RustBindings\LightWallet.cs:line 165
```

What kind of information would help you diagnose this? I've been able to repro it twice in a row (out of two attempts).

**Comment by arg0d** [comment]
Hey, sorry for the late reply. Did you figure out what was the cause? There are explicit checks in generated bindings to verify that generated bindings and library code matches. But there are some cases when [these checks are not adequate](https://github.com/mozilla/uniffi-rs/issues/1789).

**Comment by AArnott** [comment]
I'm pretty sure in my case, the rust and C# sides were just out of sync. I never saw it again after recompiling the rust code (which in my case also regenerates the C# bindings).
