### ISSUE TITLE
Empty struct causes errors in generated code

### ISSUE THREAD

**Issue by itrumper** [NordSecurity/uniffi-bindgen-cs#75]
Given the following Rust struct:
```Rust
#[derive(Record)]
struct Test {}
```

the generated C# code is:
```C#
public record Test (
) {
}

class FfiConverterTypeTest: FfiConverterRustBuffer<Test> {
    public static FfiConverterTypeTest INSTANCE = new FfiConverterTypeTest();

    public override Test Read(BigEndianStream stream) {
        return new Test(
        );
    }

    public override int AllocationSize(Test value) {
        return;
    }

    public override void Write(Test value, BigEndianStream stream) {
    }
}
```

which contains the error "CS0126	An object of a type convertible to 'int' is required". This comes from the empty return in the `AllocationSize` method. Adding a return value of 0 is I think the correct solution, as that is what Rust allocates for this struct. Thoughts?

**Comment by arg0d** [comment]
Yeah, returning 0 sounds like the right thing to do.
